### PR TITLE
Added New Acronyms

### PR DESCRIPTION
**Pull request by jakem72360**
Updated the acronyms database to feature additional acronym definitions. The added definitions primarily consist of modern acronyms used on sites such as Reddit, as well as a few older acronyms that were previously missing.

### CODE REVIEW

**Comment by keenerd** [comment]
No good.  You've used spaces instead of tabs.

**Comment by jakem72360** [comment]
My bad, I didn't realise those were tabs. I'll correct the problem.

**Comment by jakem72360** [comment]
Okay, I believe I've fixed the problem.

**Comment by keenerd** [comment]
Thanks!

**Pull request closed without merging**
